version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  client:
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client-react/
    volumes:
      - ./client-react:/app
      - /app/node_modules
  api:
    depends_on:
      - postgres
    # TODO add migrations after 'done;' below:
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python migrations/migrate.py up v1; python run-dev.py'

    build:
      dockerfile: Dockerfile.dev
      context: ./server/
    volumes:
      - ./server:/app
      - /app/venv
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASSWORD=
      # NOTE do this
      - PYTHONPATH=/app
      - HTTP_HOST=http://localhost:5000
      - NOMICS_API_KEY=foo
