version: '3'
services:
  proxy:
   depends_on:
     - client
   build:
     dockerfile: Dockerfile.prod
     context: ./proxy
   ports:
     - "80:80"
  client:
    depends_on:
      - api
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client-react/
    volumes:
      - ./client-react:/app
      - /app/node_modules
    environment:
      # TODO change this!!! Don't forget to expose the port if we can't get nginx to work with socket.io!
      - REACT_APP_SOCKET_HOST=http://fortune-game.duckdns.org:5000
      - CI=true
  api:
    # TODO add migrations after 'done;' below:
    # command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python run-dev.py'
    #command: gunicorn --bind 0.0.0.0:5000 wsgi:create_app()
    build:
      dockerfile: Dockerfile.prod
      context: ./server/
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    environment:
      - PORT=5000
      - FLASK_ENV=production
      #TODO Change to real variables/create secrets file.
      # NOTE do this
      - PYTHONPATH=/app
      - HTTP_HOST=http://fortune-game.duckdns.org:5000
      - NOMICS_API_KEY=c985caec9e0f781316d029710ef15ae2
