version: '3'
services:
  proxy:
    image: nginx:1.15-alpine
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.prod
      context: ./proxy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "8000:80"
    environment:
      - REACT_APP_SOCKET_HOST=http://localhost:5000
    volumes:
      - ./proxy/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - ./client-react/build:/var/www/build
  api:
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python migrations/migrate.py up v1; python run-dev.py'
    #command: gunicorn --bind 0.0.0.0:5000 wsgi:create_app()
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.prod
      context: ./server/
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    environment:
      - PORT=5000
      - FLASK_ENV=development
      #TODO Change to real variables/create secrets file.
      # NOTE do this
      - PYTHONPATH=/app
      #- HTTP_HOST=http://fortune-game.duckdns.org:5000
      - HTTP_HOST=http://staging.tylerstanish.com:5000
      - NOMICS_API_KEY=c985caec9e0f781316d029710ef15ae2
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
